### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by joe-getcouragenow** [sbis04/explore#7]
This is really an amazing example of how flutter can be used not just for apps

I was wondering if you had any thoughts on how to make the links work.

For example when you press "Destination", it should move to that anchor link.

**Comment by jessejay247** [comment]
The links were obviously not added, it's a demo project to showcase how flutter web can be used to build beautiful websites. I don't think this is an issue.

**Comment by sbis04** [comment]
This demo app is not covering **Navigation** in detail, so most of the links are not connected with any UI components.
